# Generated by Django 5.2.5 on 2025-09-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_experience_alter_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.IntegerField(default=0),
        ),
    ]
