# Generated by Django 5.2.5 on 2025-09-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_shortlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
