# Generated by Django 5.2.5 on 2025-09-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_shortlist_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
