# Generated by Django 5.2.5 on 2025-09-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_shortlist_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
