# Generated by Django 5.2.5 on 2025-09-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_resume_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Optional stored embedding (list of floats)', null=True),
        ),
    ]
