# Generated by Django 5.2.5 on 2025-09-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_alter_resume_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Raw extracted text from file (optional)', null=True),
        ),
    ]
