# Generated by Django 5.2.6 on 2025-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_job_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='embedding_model_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='embedding_model_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
