# Generated by Django 5.2.6 on 2025-09-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0018_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
