# Generated by Django 5.2.6 on 2025-09-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0019_application_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
