# Generated by Django 5.2.5 on 2025-09-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_job_resume_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
    ]
