# Generated by Django 5.2.6 on 2025-09-21 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_job_created_by'),
        ('resumes', '0021_job_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='resumes.job'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
