# Generated by Django 5.2.6 on 2025-09-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_alter_interview_passing_percent'),
    ]

    operations = [
    ]
