# Generated by Django 5.2.6 on 2025-09-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        ('resumes', '0019_application_candidate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='interview',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='resumes.job'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='passing_percent',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
