# Generated by Django 5.2.6 on 2025-09-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_interview_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='passing_percent',
            field=models.PositiveIntegerField(default=60, null=True),
        ),
    ]
