# Generated by Django 5.2.6 on 2025-09-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_interviewinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewinvite',
            name='reminder_15m_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewinvite',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
