# Generated by Django 5.2.6 on 2025-09-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quiz_job_delete_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
