# Generated by Django 5.2.6 on 2025-09-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_interview_duration_minutes_alter_interview_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
