# Generated by Django 5.2.6 on 2025-09-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_add_ai_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
