# Generated by Django 5.2.5 on 2025-09-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_remove_resume_email_remove_resume_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
