# Generated by Django 5.2.5 on 2025-09-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_resume_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
