# Generated by Django 5.2.6 on 2025-09-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0015_alter_application_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
