# Generated by Django 5.2.6 on 2025-09-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0016_remove_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='applied_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='score_snapshot',
        ),
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
